/* MTG Movers service worker - generated by publish_static.py */
const VERSION = '20260529153402';
const CACHE = 'mtg-movers-' + VERSION;
const SHELL = ['./', './index.html', './manifest.webmanifest',
               './icon-192.png', './icon-512.png'];
self.addEventListener('install', (e) => {
  self.skipWaiting();
  e.waitUntil(caches.open(CACHE).then(c => c.addAll(SHELL).catch(() => {})));
});
self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches.keys().then(keys => Promise.all(
      keys.filter(k => k.startsWith('mtg-movers-') && k !== CACHE).map(k => caches.delete(k))
    )).then(() => self.clients.claim())
  );
});
self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  // Cache the Chart.js library (CDN) so charts work offline after the first load.
  if (url.hostname === 'cdn.jsdelivr.net' && url.pathname.includes('chart')) {
    e.respondWith(caches.match(req).then(m => m || fetch(req).then(r => {
      const copy = r.clone();
      caches.open(CACHE).then(c => c.put(req, copy)).catch(() => {});
      return r;
    })));
    return;
  }
  if (url.origin !== self.location.origin) return;  // card images etc. -> normal network
  // Stale-while-revalidate for our own pages + data: serve the cached copy
  // INSTANTLY so the user sees something at once, fetch a fresh copy in the
  // background and store it for the next request. Falls back to index.html
  // shell if both cache and network are empty (full offline mode).
  e.respondWith(
    caches.match(req).then(cached => {
      const networkFetch = fetch(req).then(r => {
        const copy = r.clone();
        caches.open(CACHE).then(c => c.put(req, copy)).catch(() => {});
        return r;
      }).catch(() => null);
      return cached || networkFetch || caches.match('./index.html');
    })
  );
});
