/* MTG Movers service worker - generated by publish_static.py */
const VERSION = '20260529101604';
const CACHE = 'mtg-movers-' + VERSION;
const SHELL = ['./', './index.html', './manifest.webmanifest',
               './icon-192.png', './icon-512.png'];
self.addEventListener('install', (e) => {
  self.skipWaiting();
  e.waitUntil(caches.open(CACHE).then(c => c.addAll(SHELL).catch(() => {})));
});
self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches.keys().then(keys => Promise.all(
      keys.filter(k => k.startsWith('mtg-movers-') && k !== CACHE).map(k => caches.delete(k))
    )).then(() => self.clients.claim())
  );
});
self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  // Cache the Chart.js library (CDN) so charts work offline after the first load.
  if (url.hostname === 'cdn.jsdelivr.net' && url.pathname.includes('chart')) {
    e.respondWith(caches.match(req).then(m => m || fetch(req).then(r => {
      const copy = r.clone();
      caches.open(CACHE).then(c => c.put(req, copy)).catch(() => {});
      return r;
    })));
    return;
  }
  if (url.origin !== self.location.origin) return;  // card images etc. -> normal network
  // Network-first for our own pages + data: fresh when online, last snapshot offline.
  e.respondWith(
    fetch(req).then(r => {
      const copy = r.clone();
      caches.open(CACHE).then(c => c.put(req, copy)).catch(() => {});
      return r;
    }).catch(() => caches.match(req).then(m => m || caches.match('./index.html')))
  );
});
